import PDFDocument from 'pdfkit';
import { supabaseAdmin } from '../config/supabase';
import { NotFoundError, AppError } from '../lib/errors';
import { logger } from '../lib/logger';

function buildSessionsPdf(opts: {
  userName: string;
  sessions: any[];
  totalHours: number;
  verifiedHours: number;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    const W = doc.page.width - 100;
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#09090b').text('Merit', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#71717a').text('Volunteer Hour Record', 50, 78);
    doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e4e4e7').stroke();
    doc.fillColor('#09090b').fontSize(16).font('Helvetica-Bold').text(opts.userName, 50, 116);
    doc.fontSize(10).font('Helvetica').fillColor('#3f3f46');
    doc.text(`Total Hours: ${opts.totalHours.toFixed(1)}`, 50, 140);
    doc.text(`Verified: ${opts.verifiedHours.toFixed(1)}`, 200, 140);
    doc.text(`Sessions: ${opts.sessions.length}`, 340, 140);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 50, 158);
    doc.moveTo(50, 178).lineTo(545, 178).strokeColor('#e4e4e7').stroke();
    let y = 192;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#71717a');
    ['DATE', 'ORGANIZATION', 'HRS', 'STATUS', 'VERIFIED BY'].forEach((h, i) =>
      doc.text(h, [50, 130, 330, 390, 450][i], y));
    doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor('#e4e4e7').stroke();
    y += 22;
    for (const s of opts.sessions) {
      if (y > 750) { doc.addPage(); y = 50; }
      const st = s.status === 'verified' ? 'Verified' : s.status === 'disputed' ? 'Disputed' : 'Pending';
      const col = s.status === 'verified' ? '#16a34a' : s.status === 'disputed' ? '#dc2626' : '#71717a';
      doc.fillColor('#3f3f46').text(s.date ?? '', 50, y, { width: 75 });
      doc.text(s.org?.name ?? '', 130, y, { width: 195, ellipsis: true });
      doc.text(Number(s.hours).toFixed(1), 330, y, { width: 50 });
      doc.fillColor(col).text(st, 390, y, { width: 55 });
      doc.fillColor('#3f3f46').text(s.verified_by ?? s.supervisor_name ?? '', 450, y, { width: 95, ellipsis: true });
      doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor('#f4f4f5').stroke();
      y += 18;
    }
    doc.fontSize(8).fillColor('#a1a1aa')
      .text('Generated by Merit · merit.app', 50, doc.page.height - 40, { align: 'center', width: W });
    doc.end();
  });
}

function buildGrantReportPdf(opts: {
  chapterName: string;
  period: string;
  totalHours: number;
  verifiedHours: number;
  memberCount: number;
  sessions: any[];
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    const W = doc.page.width - 100;
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#09090b').text('Merit', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#71717a').text('Grant Report', 50, 78);
    doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e4e4e7').stroke();
    doc.fillColor('#09090b').fontSize(16).font('Helvetica-Bold').text(opts.chapterName, 50, 116);
    doc.fontSize(10).font('Helvetica').fillColor('#3f3f46');
    doc.text(`Period: ${opts.period}`, 50, 140);
    doc.text(`Members: ${opts.memberCount}`, 260, 140);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 400, 140);
    doc.roundedRect(50, 160, W, 52, 6).fillColor('#f4f4f5').fill();
    doc.fillColor('#09090b').fontSize(20).font('Helvetica-Bold');
    doc.text(opts.totalHours.toFixed(1), 80, 170);
    doc.text(opts.verifiedHours.toFixed(1), 260, 170);
    doc.text(String(opts.memberCount), 430, 170);
    doc.fontSize(9).font('Helvetica').fillColor('#71717a');
    doc.text('Total Hours', 80, 197); doc.text('Verified Hours', 260, 197); doc.text('Members', 430, 197);
    doc.moveTo(50, 226).lineTo(545, 226).strokeColor('#e4e4e7').stroke();
    let y = 240;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#71717a');
    ['STUDENT', 'ORGANIZATION', 'DATE', 'HRS', 'STATUS'].forEach((h, i) =>
      doc.text(h, [50, 185, 345, 405, 455][i], y));
    doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor('#e4e4e7').stroke();
    y += 22;
    for (const s of opts.sessions) {
      if (y > 750) { doc.addPage(); y = 50; }
      const st = s.status === 'verified' ? 'Verified' : s.status === 'disputed' ? 'Disputed' : 'Pending';
      const col = s.status === 'verified' ? '#16a34a' : s.status === 'disputed' ? '#dc2626' : '#71717a';
      doc.fillColor('#3f3f46').text(s.studentName ?? '', 50, y, { width: 130, ellipsis: true });
      doc.text(s.orgName ?? '', 185, y, { width: 155, ellipsis: true });
      doc.text(s.date ?? '', 345, y, { width: 55 });
      doc.text(Number(s.hours).toFixed(1), 405, y, { width: 45 });
      doc.fillColor(col).text(st, 455, y, { width: 85 });
      doc.moveTo(50, y + 14).lineTo(545, y + 14).strokeColor('#f4f4f5').stroke();
      y += 18;
    }
    doc.fontSize(8).fillColor('#a1a1aa')
      .text('Generated by Merit · merit.app', 50, doc.page.height - 40, { align: 'center', width: W });
    doc.end();
  });
}

async function uploadAndSign(buffer: Buffer, path: string): Promise<string> {
  const { error } = await supabaseAdmin.storage
    .from('exports')
    .upload(path, buffer, { contentType: 'application/pdf', upsert: true });

  if (error) {
    logger.warn({ path }, 'storage_upload_failed_returning_mock_url');
    return `mock://exports/${path}`;
  }

  const { data: signed } = await supabaseAdmin.storage
    .from('exports')
    .createSignedUrl(path, 3600);

  return (signed as any)?.signedUrl ?? `mock://exports/${path}`;
}

export async function exportSessionsPdf(userId: string): Promise<{ url: string }> {
  const { data: user } = await supabaseAdmin
    .from('users').select('name, plan').eq('id', userId).maybeSingle();

  if (!user) throw new NotFoundError('User');
  const u = user as any;
  if (!['pro', 'premium', 'institutional'].includes(u.plan)) {
    throw new AppError('plan_required', 'PDF export requires a Pro plan or higher.', 403);
  }

  const { data: sessions } = await supabaseAdmin
    .from('sessions')
    .select('date, hours, status, supervisor_name, verified_by, org:organizations(name)')
    .eq('user_id', userId).is('deleted_at', null).order('date', { ascending: false });

  const rows = (sessions as any[] | null) ?? [];
  const totalHours = rows.reduce((s: number, r: any) => s + Number(r.hours), 0);
  const verifiedHours = rows.filter((r: any) => r.status === 'verified')
    .reduce((s: number, r: any) => s + Number(r.hours), 0);

  const buffer = await buildSessionsPdf({ userName: u.name, sessions: rows, totalHours, verifiedHours });
  const url = await uploadAndSign(buffer, `users/${userId}/sessions-${Date.now()}.pdf`);
  logger.info({ userId }, 'sessions_pdf_exported');
  return { url };
}

export async function exportGrantReportPdf(
  userId: string,
  opts: { from?: string; to?: string } = {},
): Promise<{ url: string }> {
  const { getGrantReport, getCoordinatorChapterId } = await import('./admin.service');
  const chapterId = await getCoordinatorChapterId(userId);
  const report = await getGrantReport(userId, opts);
  const buffer = await buildGrantReportPdf(report as any);
  const url = await uploadAndSign(buffer, `chapters/${chapterId}/grant-report-${Date.now()}.pdf`);
  logger.info({ userId, chapterId }, 'grant_report_pdf_exported');
  return { url };
}
