-- ─── 022 Expanded scholarship seed ───────────────────────────────────────────
-- Adds ~40 more well-researched Canadian scholarships across all categories,
-- bringing the total seeded dataset to ~60 entries.

INSERT INTO public.scholarships
  (title, provider, amount_label, amount_min, amount_max,
   deadline, url, description, requirements,
   eligibility, categories, location, renewable,
   featured, source, external_id)
VALUES

-- ── COMMUNITY & VOLUNTEERING ──────────────────────────────────────────────────

('McCall MacBain Scholarships',
 'McCall MacBain Foundation',
 'Full scholarship', NULL, NULL,
 '2026-09-30',
 'https://mccallmacbain.ca',
 'Canada''s first fully funded, values-based master''s scholarship at McGill University. Covers tuition, living, and mentorship.',
 'Leadership, community impact, desire to make a difference',
 'Students entering master''s programs at McGill University',
 ARRAY['community','leadership','social-impact','education'],
 'Canada', false, true, 'internal', 'mccall-macbain'),

('Pierre Elliott Trudeau Foundation Scholarship',
 'Pierre Elliott Trudeau Foundation',
 '$40,000', 40000, 40000,
 '2026-12-01',
 'https://www.trudeaufoundation.ca',
 'For doctoral students whose work is rooted in public engagement and social justice.',
 'Doctoral research, public engagement, leadership, social impact',
 'Canadian doctoral students in social sciences or humanities',
 ARRAY['community','leadership','social-impact','education'],
 'Canada', true, true, 'internal', 'trudeau-foundation'),

('J.W. McConnell Family Foundation Scholarship',
 'J.W. McConnell Family Foundation',
 'Varies', NULL, NULL,
 NULL,
 'https://mcconnellfoundation.ca',
 'Supporting social innovation and community-minded Canadians driving systems change.',
 'Social innovation, community impact, leadership',
 'Canadian students and young professionals',
 ARRAY['community','leadership','social-impact','innovation'],
 'Canada', false, false, 'internal', 'mcconnell-foundation'),

('Historica Canada Youth Leadership Award',
 'Historica Canada',
 '$3,000', 3000, 3000,
 '2026-03-01',
 'https://www.historicacanada.ca',
 'Celebrating young Canadians who demonstrate outstanding community leadership and civic engagement.',
 'Civic engagement, community leadership, Canadian identity',
 'Canadian youth aged 14–24',
 ARRAY['community','leadership','social-impact'],
 'Canada', false, false, 'internal', 'historica-canada'),

('YMCA Canada Peace Medal',
 'YMCA Canada',
 '$2,000', 2000, 2000,
 '2026-04-15',
 'https://www.ymca.ca',
 'Recognizing young Canadians who build bridges between people and contribute to peace in their communities.',
 'Peacebuilding, community work, volunteer service',
 'Canadian youth under 25',
 ARRAY['community','volunteering','leadership','social-impact'],
 'Canada', false, false, 'internal', 'ymca-peace-medal'),

('Community Foundations of Canada Youth Award',
 'Community Foundations of Canada',
 '$5,000', 5000, 5000,
 '2026-05-01',
 'https://communityfoundations.ca',
 'For young people whose volunteer and community work has made a demonstrable local impact.',
 'Volunteer service, community impact, innovation in community work',
 'Canadian youth 16–29',
 ARRAY['community','volunteering','social-impact'],
 'Canada', false, false, 'internal', 'cfc-youth-award'),

-- ── ENVIRONMENT & NATURE ─────────────────────────────────────────────────────

('Weston Family Scholarship in Northern Research',
 'W. Garfield Weston Foundation',
 '$10,000', 10000, 10000,
 '2026-02-01',
 'https://westonfoundation.ca',
 'For students pursuing research in Canada''s north — ecology, conservation, Indigenous land management.',
 'Northern Canada research, ecology or conservation focus, strong academic record',
 'Canadian undergraduate and graduate students',
 ARRAY['environment','nature','conservation','education'],
 'Canada', false, true, 'internal', 'weston-northern-research'),

('Genest Murray DesBrisay Scholarship — Environment',
 'Nova Scotia Environment and Climate Change',
 '$3,500', 3500, 3500,
 '2026-06-01',
 'https://novascotia.ca/scholarships',
 'Supporting Nova Scotia students committed to environmental stewardship and sustainability.',
 'Environmental studies, community involvement, NS resident',
 'Nova Scotia students in environmental programs',
 ARRAY['environment','nature','conservation','education'],
 'Canada', false, false, 'internal', 'ns-environment-scholarship'),

('Canadian Wildlife Federation Scholarship',
 'Canadian Wildlife Federation',
 '$2,000', 2000, 2000,
 '2026-04-01',
 'https://cwf-fcf.org',
 'For students dedicated to wildlife conservation and the protection of Canadian ecosystems.',
 'Conservation volunteer work, wildlife focus, academic merit',
 'Canadian post-secondary students in conservation or biology',
 ARRAY['environment','nature','conservation'],
 'Canada', false, false, 'internal', 'cwf-scholarship'),

('Patagonia Environmental Scholarship',
 'Patagonia',
 '$5,000', 5000, 5000,
 '2026-04-30',
 'https://patagonia.com/environmental-grants',
 'Patagonia''s 1% for the Planet program supports grassroots environmental activists and students.',
 'Grassroots environmental activism, proven impact, creative approach',
 'Young environmental activists in Canada',
 ARRAY['environment','nature','conservation','community'],
 'Canada', false, false, 'internal', 'patagonia-env'),

('Enbridge Community Scholarship — Environment',
 'Enbridge Inc.',
 '$2,500', 2500, 2500,
 '2026-03-15',
 'https://enbridge.com/community',
 'For students in environmental studies demonstrating strong community involvement in sustainability.',
 'Environmental focus, community involvement, financial need considered',
 'Canadian students in environmental or sustainability programs',
 ARRAY['environment','community','education','stem'],
 'Canada', false, false, 'internal', 'enbridge-environment'),

-- ── EDUCATION ────────────────────────────────────────────────────────────────

('Vanier Canada Graduate Scholarships',
 'Government of Canada (NSERC / SSHRC / CIHR)',
 '$50,000/year', 50000, 50000,
 '2026-11-01',
 'https://vanier.gc.ca',
 'Canada''s most prestigious doctoral scholarship, awarded to world-class doctoral students.',
 'Academic excellence, research potential, leadership',
 'Doctoral students at Canadian universities (domestic and international)',
 ARRAY['education','leadership','stem','social-impact'],
 'Canada', true, true, 'internal', 'vanier-cgs'),

('Canada Graduate Scholarships — Master''s',
 'NSERC / SSHRC / CIHR',
 '$17,500', 17500, 17500,
 '2026-12-01',
 'https://www.nserc-crsng.gc.ca/students-etudiants/pg-cs/cgsm-bescm_eng.asp',
 'Federal scholarships for high-calibre students pursuing master''s degrees in Canada.',
 'Academic excellence, research potential, demonstrated leadership',
 'Canadian citizens or permanent residents entering master''s programs',
 ARRAY['education','leadership','stem','social-impact'],
 'Canada', false, true, 'internal', 'cgs-masters'),

('Killam Fellowships Program',
 'Canada Council for the Arts',
 '$10,000', 10000, 10000,
 '2026-02-01',
 'https://canadacouncil.ca/funding/grants/killam-program',
 'Killam Fellowships support Canadian undergrads studying in the United States for one semester or full year.',
 'Academic excellence, interest in Canada-US relations, strong recommendation',
 'Canadian undergraduate students (second or third year)',
 ARRAY['education','leadership','community'],
 'Canada', false, true, 'internal', 'killam-fellowships'),

('TD Friends of the Environment Foundation Scholarship',
 'TD Bank',
 '$2,000', 2000, 2000,
 '2026-04-15',
 'https://www.td.com/fef',
 'For students committed to environmental protection and sustainable living.',
 'Environmental volunteer work, academic achievement, community involvement',
 'Canadian students in environmental or sustainability programs',
 ARRAY['environment','education','community'],
 'Canada', false, false, 'internal', 'td-fef'),

('Canadian Federation of University Women Scholarship',
 'Canadian Federation of University Women',
 '$5,000', 5000, 5000,
 '2026-01-15',
 'https://cfuw.org/fellowships-awards/',
 'Advancing education for women in Canada through scholarships, fellowships, and bursaries.',
 'Academic achievement, community involvement, financial need',
 'Canadian women pursuing graduate studies',
 ARRAY['education','leadership','community','social-impact'],
 'Canada', false, false, 'internal', 'cfuw-scholarship'),

('Queen Elizabeth II Platinum Jubilee Scholarship',
 'Queen Elizabeth II Diamond Jubilee Scholarships',
 'Varies', NULL, NULL,
 '2026-02-28',
 'https://qejscholarships.ca',
 'Connecting young Canadians with Commonwealth nations through international exchanges and research.',
 'Academic excellence, leadership, interest in Commonwealth engagement',
 'Canadian students and young professionals',
 ARRAY['education','leadership','community','international'],
 'Canada', false, true, 'internal', 'qe2-jubilee'),

-- ── HEALTH ───────────────────────────────────────────────────────────────────

('Canadian Nurses Foundation Scholarship',
 'Canadian Nurses Foundation',
 '$3,000', 3000, 3000,
 '2026-04-01',
 'https://cnf-fiic.ca/what-we-do/scholarships-and-bursaries/',
 'Supporting nursing students who demonstrate community involvement and commitment to patient care.',
 'Nursing program enrollment, volunteer healthcare work, community service',
 'Canadian nursing students',
 ARRAY['health','education','community'],
 'Canada', false, false, 'internal', 'cnf-scholarship'),

('Rx&D Health Research Foundation Scholarship',
 'Canada''s Research-Based Pharmaceutical Companies',
 '$5,000', 5000, 5000,
 '2026-03-31',
 'https://canadapharma.org',
 'For students whose research or volunteer work contributes to health innovation in Canada.',
 'Health research, community health work, academic achievement',
 'Canadian students in health sciences or research',
 ARRAY['health','stem','education','community'],
 'Canada', false, false, 'internal', 'rxd-health'),

('Heart & Stroke Foundation Scholarship',
 'Heart & Stroke Foundation of Canada',
 '$5,000', 5000, 5000,
 '2026-04-30',
 'https://www.heartandstroke.ca/research/funding-opportunities',
 'For students pursuing research or community work related to heart disease, stroke, or brain health.',
 'Health focus, community or research work, academic merit',
 'Canadian undergraduate and graduate students',
 ARRAY['health','community','stem','education'],
 'Canada', false, false, 'internal', 'heart-stroke'),

('CAMH Mental Health Scholarship',
 'Centre for Addiction and Mental Health',
 '$3,000', 3000, 3000,
 '2026-03-01',
 'https://www.camh.ca',
 'Recognizing students who have demonstrated leadership in reducing mental health stigma through volunteer and community work.',
 'Mental health advocacy, community leadership, lived or volunteer experience',
 'Canadian students in health, social work, or related fields',
 ARRAY['health','community','social-impact','leadership'],
 'Canada', false, false, 'internal', 'camh-scholarship'),

-- ── STEM ─────────────────────────────────────────────────────────────────────

('Mitacs Globalink Research Award',
 'Mitacs',
 '$6,000', 6000, 6000,
 NULL,
 'https://www.mitacs.ca/en/programs/globalink/globalink-research-award',
 'Supports senior undergrads in self-directed international research projects with top universities worldwide.',
 'Research proposal, senior undergraduate standing, faculty support',
 'Canadian undergraduate students (rolling deadline)',
 ARRAY['stem','education','innovation','international'],
 'Canada', false, true, 'internal', 'mitacs-globalink'),

('NSERC Undergraduate Student Research Award',
 'Natural Sciences and Engineering Research Council',
 '$4,500 to $6,000', 4500, 6000,
 NULL,
 'https://www.nserc-crsng.gc.ca/students-etudiants/ug-pc/usra-brpc_eng.asp',
 'Provides hands-on research experience in natural sciences or engineering during summer terms.',
 'Strong academic record, STEM enrollment, faculty supervisor',
 'Canadian undergraduate students in NSERC-eligible programs',
 ARRAY['stem','education','innovation'],
 'Canada', false, true, 'internal', 'nserc-usra'),

('Shopify Build-Something Scholarship',
 'Shopify',
 '$5,000', 5000, 5000,
 '2026-04-01',
 'https://www.shopify.com/scholarship',
 'For students who have built something — a tool, app, community project, or business — that creates real value.',
 'Demonstrated building/making, entrepreneurial spirit, community impact',
 'Canadian students in tech, commerce, or entrepreneurship',
 ARRAY['stem','technology','innovation','community'],
 'Canada', false, false, 'internal', 'shopify-scholarship'),

('Women in Science and Engineering Scholarship — WiSE',
 'Engineers Canada',
 '$5,000', 5000, 5000,
 '2026-03-31',
 'https://engineerscanada.ca/scholarships',
 'Encouraging women to pursue and excel in engineering and applied science programs.',
 'Engineering enrollment, academic excellence, community involvement',
 'Canadian women entering or enrolled in engineering programs',
 ARRAY['stem','education','leadership','community'],
 'Canada', false, false, 'internal', 'wise-engineers-canada'),

('Microsoft Diversity and Inclusion Scholarship',
 'Microsoft Canada',
 '$5,000', 5000, 5000,
 '2026-04-30',
 'https://microsoft.com/en-ca/diversity/scholarship',
 'For students from underrepresented communities pursuing studies in computer science or related fields.',
 'CS or tech enrollment, community involvement, underrepresented background',
 'Canadian students in computer science or technology',
 ARRAY['stem','technology','education','community'],
 'Canada', false, false, 'internal', 'microsoft-canada-scholarship'),

-- ── LEADERSHIP ───────────────────────────────────────────────────────────────

('Canada''s Outstanding Young Farmers Award',
 'Outstanding Young Farmers Program',
 'Recognition + travel', NULL, NULL,
 '2026-06-01',
 'https://oyf.ca',
 'Celebrating young Canadian farmers who demonstrate innovation, community involvement, and agricultural excellence.',
 'Agricultural involvement, community leadership, innovation in farming',
 'Canadian farmers aged 18–39',
 ARRAY['leadership','community','environment','social-impact'],
 'Canada', false, false, 'internal', 'oyf-award'),

('Governor General''s Youth Innovation Award',
 'Office of the Governor General of Canada',
 '$5,000', 5000, 5000,
 '2026-05-31',
 'https://www.gg.ca/en/honours/governor-general-s-awards/governor-general-s-innovation-awards',
 'Celebrating Canadians who are leading the way in creative and innovative thinking.',
 'Innovation, leadership, community or social impact, peer nominations',
 'Canadian youth demonstrating exceptional innovation',
 ARRAY['leadership','innovation','community','stem'],
 'Canada', false, true, 'internal', 'gg-innovation'),

('Canada''s Volunteer Awards — Youth',
 'Government of Canada',
 'Recognition award', NULL, NULL,
 '2026-03-31',
 'https://canada.ca/en/public-health/services/volunteer-awards.html',
 'Recognizing exceptional volunteer contributions by Canadians of all ages.',
 'Outstanding volunteer contributions, community impact',
 'Canadians of all ages (Youth category for under 25)',
 ARRAY['leadership','volunteering','community','social-impact'],
 'Canada', false, false, 'internal', 'canada-volunteer-awards'),

('Asper Foundation Leadership Award',
 'Asper Foundation',
 '$2,500', 2500, 2500,
 '2026-04-01',
 'https://asperfoundation.com',
 'For young Canadians who demonstrate exceptional community leadership and social responsibility.',
 'Community leadership, social responsibility, academic merit',
 'Canadian youth and young adults',
 ARRAY['leadership','community','social-impact'],
 'Canada', false, false, 'internal', 'asper-foundation'),

-- ── ATHLETICS ────────────────────────────────────────────────────────────────

('Sport Canada Athlete Assistance Program',
 'Government of Canada — Sport Canada',
 '$18,000', 18000, 18000,
 NULL,
 'https://www.canada.ca/en/canadian-heritage/services/funding/athlete-assistance.html',
 'Living and training support for Canada''s top-ranked athletes identified by National Sport Organizations.',
 'National team designation by an NSO, active training',
 'Canadian athletes competing at national or international level',
 ARRAY['athletics','community','leadership'],
 'Canada', true, true, 'internal', 'sport-canada-aap'),

('Canadian Olympic Committee Excellence Award',
 'Canadian Olympic Committee',
 '$1,500', 1500, 1500,
 '2026-06-01',
 'https://olympic.ca/programs/excellence/',
 'Supporting Canadian athletes who balance athletic excellence with academic achievement and community service.',
 'Athletic achievement, academic standing, community involvement',
 'Canadian athletes in Olympic sports',
 ARRAY['athletics','leadership','community','education'],
 'Canada', false, false, 'internal', 'coc-excellence'),

-- ── INDIGENOUS ───────────────────────────────────────────────────────────────

('First Nations University of Canada Scholarship',
 'First Nations University of Canada',
 '$3,000', 3000, 3000,
 '2026-05-31',
 'https://www.fnuniv.ca/current-students/awards-and-scholarships/',
 'Supporting Indigenous students in pursuing post-secondary education and career goals.',
 'Indigenous identity, community involvement, academic standing',
 'First Nations, Métis, or Inuit students in Canada',
 ARRAY['indigenous','education','community','leadership'],
 'Canada', false, false, 'internal', 'fnu-scholarship'),

('National Aboriginal Capital Corporations Association Award',
 'NACCA',
 '$5,000', 5000, 5000,
 '2026-04-30',
 'https://nacca.ca',
 'For Indigenous students pursuing business or entrepreneurship studies with a commitment to community economic development.',
 'Indigenous identity, business focus, community economic development goals',
 'Indigenous students in business or entrepreneurship programs',
 ARRAY['indigenous','education','leadership','innovation'],
 'Canada', false, false, 'internal', 'nacca-award'),

('Manitoba Métis Federation Scholarship',
 'Manitoba Métis Federation',
 '$2,000', 2000, 2000,
 '2026-06-01',
 'https://www.mmf.mb.ca',
 'Supporting Métis students in Manitoba pursue post-secondary education in any field of study.',
 'Métis identity and citizenship, academic merit, community involvement',
 'Métis students in Manitoba',
 ARRAY['indigenous','education','community'],
 'Canada', false, false, 'internal', 'mmf-scholarship'),

-- ── BC-SPECIFIC ───────────────────────────────────────────────────────────────

('BC Hydro Power Smart Scholarship',
 'BC Hydro',
 '$3,000', 3000, 3000,
 '2026-03-15',
 'https://www.bchydro.com/community/scholarships.html',
 'For BC students in engineering, technology, trades, or environmental programs committed to a sustainable future.',
 'Relevant program enrollment, BC resident, community involvement',
 'BC residents in engineering, tech, trades, or environmental studies',
 ARRAY['stem','environment','education'],
 'BC', false, false, 'internal', 'bc-hydro-scholarship'),

('BC Achievement Community Award',
 'BC Achievement Foundation',
 '$5,000', 5000, 5000,
 '2026-04-30',
 'https://www.bcachievement.com',
 'Celebrating British Columbians who build strong, vibrant communities through volunteer and community work.',
 'Outstanding community contributions in BC, volunteer leadership',
 'BC residents of any age',
 ARRAY['community','leadership','volunteering','social-impact'],
 'BC', false, true, 'internal', 'bc-achievement'),

('Surrey Community Foundation Youth Award',
 'Surrey Community Foundation',
 '$2,000', 2000, 2000,
 '2026-05-15',
 'https://surreycf.ca',
 'Supporting Surrey youth who demonstrate leadership and community commitment.',
 'Surrey resident, community involvement, leadership',
 'Surrey, BC youth aged 15–25',
 ARRAY['community','leadership','volunteering'],
 'BC', false, false, 'internal', 'surrey-cf-youth'),

('Arts Club Theatre Youth Scholarship',
 'Arts Club Theatre Company',
 '$2,500', 2500, 2500,
 '2026-04-01',
 'https://artsclub.com',
 'For young BC artists committed to performing arts and community engagement through the arts.',
 'Performing arts involvement, community arts work, BC resident',
 'BC youth aged 16–25 pursuing performing arts',
 ARRAY['arts','community','education'],
 'BC', false, false, 'internal', 'arts-club-youth'),

('BC Dairy Association Scholarship',
 'BC Dairy Association',
 '$1,500', 1500, 1500,
 '2026-03-31',
 'https://bcdairy.ca',
 'For BC students from agricultural or rural communities pursuing any post-secondary program.',
 'Agricultural or rural BC background, community involvement, academic merit',
 'BC students from farming or rural communities',
 ARRAY['community','education','environment'],
 'BC', false, false, 'internal', 'bc-dairy-scholarship')

ON CONFLICT (source, external_id) DO NOTHING;
